routing:
  compose:
    upstream:
      host: nginx-sidecar
      port: 3007
    limit: 10000
    slo: 16
#  home:
#    upstream:
#      host: nginx-sidecar
#      port: 3007
#    limit: 11
#    slo: 20
#  user:
#    upstream:
#      host: nginx-sidecar
#      port: 3007
#    limit: 9
#    slo: 20
mapping:
  compose:
    downstreams:
      - compose
    listen_port: 3000
#  home:
#    downstreams:
#      - home
#    listen_port: 3008
#  user:
#    downstreams:
#      - user
#    listen_port: 3009
ring_size: 4000
buffer_count: 16384
buffer_size: 10000
ingress_pool_connections: 100
num_threads: 1
egress_listener_port: 3000
ingress_listener_port: 4000
ingress_upstream_host: 172.17.0.1
ingress_upstream_port: 2000
is_ingress: True
is_frontend: False
ppm_limit: 2
report_latency: True
name: ingress