apiVersion: v1
kind: Pod
metadata:
  name: ms-12657
  labels:
    app: ms-12657
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-12657:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-12657
  labels:
    app: ms-12657
spec:
  selector:
    app: ms-12657
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-14758
  labels:
    app: ms-14758
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-14758:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-14758
  labels:
    app: ms-14758
spec:
  selector:
    app: ms-14758
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-18750
  labels:
    app: ms-18750
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-18750:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-18750
  labels:
    app: ms-18750
spec:
  selector:
    app: ms-18750
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-19439
  labels:
    app: ms-19439
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-19439:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-19439
  labels:
    app: ms-19439
spec:
  selector:
    app: ms-19439
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-21298
  labels:
    app: ms-21298
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-21298:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-21298
  labels:
    app: ms-21298
spec:
  selector:
    app: ms-21298
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-25781
  labels:
    app: ms-25781
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-25781:latest
    resources:
      requests:
        cpu: "2"
      limits:
        cpu: "2"
    env:
    - name: GOMAXPROCS
      value: "2"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-25781
  labels:
    app: ms-25781
spec:
  selector:
    app: ms-25781
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-25806
  labels:
    app: ms-25806
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-25806:latest
    resources:
      requests:
        cpu: "3"
      limits:
        cpu: "3"
    env:
    - name: GOMAXPROCS
      value: "3"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-25806
  labels:
    app: ms-25806
spec:
  selector:
    app: ms-25806
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-2687
  labels:
    app: ms-2687
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-2687:latest
    resources:
      requests:
        cpu: "3"
      limits:
        cpu: "3"
    env:
    - name: GOMAXPROCS
      value: "3"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-2687
  labels:
    app: ms-2687
spec:
  selector:
    app: ms-2687
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-33572
  labels:
    app: ms-33572
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-33572:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-33572
  labels:
    app: ms-33572
spec:
  selector:
    app: ms-33572
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-38190
  labels:
    app: ms-38190
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-38190:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-38190
  labels:
    app: ms-38190
spec:
  selector:
    app: ms-38190
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-40087
  labels:
    app: ms-40087
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-40087:latest
    resources:
      requests:
        cpu: "3"
      limits:
        cpu: "3"
    env:
    - name: GOMAXPROCS
      value: "3"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-40087
  labels:
    app: ms-40087
spec:
  selector:
    app: ms-40087
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-41667
  labels:
    app: ms-41667
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-41667:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-41667
  labels:
    app: ms-41667
spec:
  selector:
    app: ms-41667
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-43032
  labels:
    app: ms-43032
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-43032:latest
    resources:
      requests:
        cpu: "3"
      limits:
        cpu: "3"
    env:
    - name: GOMAXPROCS
      value: "3"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-43032
  labels:
    app: ms-43032
spec:
  selector:
    app: ms-43032
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-43754
  labels:
    app: ms-43754
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-43754:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-43754
  labels:
    app: ms-43754
spec:
  selector:
    app: ms-43754
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-44246
  labels:
    app: ms-44246
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-44246:latest
    resources:
      requests:
        cpu: "3"
      limits:
        cpu: "3"
    env:
    - name: GOMAXPROCS
      value: "3"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-44246
  labels:
    app: ms-44246
spec:
  selector:
    app: ms-44246
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-45067
  labels:
    app: ms-45067
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-45067:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-45067
  labels:
    app: ms-45067
spec:
  selector:
    app: ms-45067
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-51783
  labels:
    app: ms-51783
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-51783:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-51783
  labels:
    app: ms-51783
spec:
  selector:
    app: ms-51783
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-51787
  labels:
    app: ms-51787
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-51787:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-51787
  labels:
    app: ms-51787
spec:
  selector:
    app: ms-51787
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-53792
  labels:
    app: ms-53792
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-53792:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-53792
  labels:
    app: ms-53792
spec:
  selector:
    app: ms-53792
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-56113
  labels:
    app: ms-56113
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-56113:latest
    resources:
      requests:
        cpu: "4"
      limits:
        cpu: "4"
    env:
    - name: GOMAXPROCS
      value: "4"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-56113
  labels:
    app: ms-56113
spec:
  selector:
    app: ms-56113
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-5720
  labels:
    app: ms-5720
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-5720:latest
    resources:
      requests:
        cpu: "3"
      limits:
        cpu: "3"
    env:
    - name: GOMAXPROCS
      value: "3"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-5720
  labels:
    app: ms-5720
spec:
  selector:
    app: ms-5720
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-58796
  labels:
    app: ms-58796
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-58796:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-58796
  labels:
    app: ms-58796
spec:
  selector:
    app: ms-58796
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-62039
  labels:
    app: ms-62039
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-62039:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-62039
  labels:
    app: ms-62039
spec:
  selector:
    app: ms-62039
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-64512-grpc
  labels:
    app: ms-64512-grpc
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-64512-grpc:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-64512-grpc
  labels:
    app: ms-64512-grpc
spec:
  selector:
    app: ms-64512-grpc
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-66921
  labels:
    app: ms-66921
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-66921:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-66921
  labels:
    app: ms-66921
spec:
  selector:
    app: ms-66921
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-67465
  labels:
    app: ms-67465
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-67465:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-67465
  labels:
    app: ms-67465
spec:
  selector:
    app: ms-67465
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-70124
  labels:
    app: ms-70124
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-70124:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-70124
  labels:
    app: ms-70124
spec:
  selector:
    app: ms-70124
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-7103
  labels:
    app: ms-7103
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-7103:latest
    resources:
      requests:
        cpu: "2"
      limits:
        cpu: "2"
    env:
    - name: GOMAXPROCS
      value: "2"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-7103
  labels:
    app: ms-7103
spec:
  selector:
    app: ms-7103
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: ms-9105
  labels:
    app: ms-9105
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-ms-9105:latest
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
    env:
    - name: GOMAXPROCS
      value: "1"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-9105
  labels:
    app: ms-9105
spec:
  selector:
    app: ms-9105
  ports:
  - name: grpc
    port: 2000
    targetPort: 2000
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: rajomon-client
  labels:
    app: rajomon-client
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alibaba-large-rajomon-client:latest
    resources:
      requests:
        cpu: "2"
      limits:
        cpu: "2"
    env:
    - name: GOMAXPROCS
      value: "2"
    envFrom:
    - configMapRef:
        name: alibaba-large-config
    ports:
    - containerPort: 2007
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-entry
  labels:
    app: rajomon-client
spec:
  type: NodePort
  selector:
    app: rajomon-client
  ports:
  - name: http
    port: 2007
    targetPort: 2007
    nodePort: 3000
    protocol: TCP
