apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-25781
  labels:
    app: ms-25781
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-25781
  template:
    metadata:
      labels:
        app: ms-25781
    spec:
      containers:
      - name: app
        image: alibaba-large-ms-25781:latest
        resources:
          requests:
            cpu: "3"
          limits:
            cpu: "3"
        env:
        - name: GOMAXPROCS
          value: "3"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: alibaba-large-config
        ports:
        - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-25781
  labels:
    app: ms-25781
spec:
  clusterIP: None
  selector:
    app: ms-25781
  ports:
  - name: http
    port: 2000
    targetPort: 2000
    protocol: TCP
