apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-43754
  labels:
    app: ms-43754
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-43754
  template:
    metadata:
      labels:
        app: ms-43754
    spec:
      containers:
      - name: app
        image: alibaba-large-ms-43754:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "4"
          limits:
            cpu: "4"
        env:
        - name: GOMAXPROCS
          value: "4"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: alibaba-large-config
        ports:
        - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: alibaba-large-ms-43754
  labels:
    app: ms-43754
spec:
  clusterIP: None
  selector:
    app: ms-43754
  ports:
  - name: http
    port: 2000
    targetPort: 2000
    protocol: TCP
