apiVersion: v1
kind: Pod
metadata:
  name: ingress
  labels:
    app: ingress
spec:
  containers:
  - name: sidecar
    image: sidecar-sidecar:latest
    env:
    - name: PROC_NAME
      value: "ingress-sidecar"
    - name: GLOG_logtostderr
      value: "1"
    resources:
      requests:
        cpu: "6"
      limits:
        cpu: "6"
    volumeMounts:
    - name: config-volume
      mountPath: /config.yaml
      subPath: ingress.yaml
    ports:
    - containerPort: 4000
    - containerPort: 3000
  
  volumes:
  - name: config-volume
    configMap:
      name: sidecar-configs

---
apiVersion: v1
kind: Service
metadata:
  name: social-ingress
  labels:
    app: ingress
spec:
  type: NodePort
  selector:
    app: ingress
  ports:
  - name: sidecar-grpc
    port: 3000
    targetPort: 3000
    nodePort: 3000
    protocol: TCP
