services:

  frontend-sidecar:
    image: sidecar-sidecar:latest
    container_name: frontend-sidecar
    restart: no
    environment:
      - GLOG_logtostderr=1
#      - GLOG_v=1
    volumes:
      - ./.configs/frontend.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4000:4000" # egress_listener_port
      - "3000:3000"   # ingress_listener_port
    privileged: true
    cpuset: "22,23"
  
  profile-sidecar:
    image: sidecar-sidecar:latest
    container_name: profile-sidecar
    restart: no
    environment:
      - GLOG_logtostderr=1
#      - GLOG_v=1
    volumes:
      - ./.configs/profile.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4001:4001" # egress_listener_port
      - "3001:3001"   # ingress_listener_port
    privileged: true
    cpuset: "24,25"
  
  reservation-sidecar:
    image: sidecar-sidecar:latest
    container_name: reservation-sidecar
    restart: no
    environment:
      - GLOG_logtostderr=1
#      - GLOG_v=1
    volumes:
      - ./.configs/reservation.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4002:4002" # egress_listener_port
      - "3002:3002"   # ingress_listener_port
    privileged: true
    cpuset: "26,27"
  
  search-sidecar:
    image: sidecar-sidecar:latest
    container_name: search-sidecar
    restart: no
    environment:
      - GLOG_logtostderr=1
#      - GLOG_v=1
    volumes:
      - ./.configs/search.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4005:4005" # egress_listener_port
      - "3005:3005"   # ingress_listener_port
    privileged: true
    cpuset: "28,29"
  
  geo-sidecar:
    image: sidecar-sidecar:latest
    container_name: geo-sidecar
    restart: no
    environment:
      - GLOG_logtostderr=1
#      - GLOG_v=1
    volumes:
      - ./.configs/geo.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4004:4004" # egress_listener_port
      - "3004:3004"   # ingress_listener_port
    privileged: true
    cpuset: "30,31"
  
  rate-sidecar:
    image: sidecar-sidecar:latest
    container_name: rate-sidecar
    restart: no
    environment:
      - GLOG_logtostderr=1
#      - GLOG_v=1
    volumes:
      - ./.configs/rate.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4003:4003" # egress_listener_port
      - "3003:3003"   # ingress_listener_port
    privileged: true
    cpuset: "32,33"
  
  user-sidecar:
    image: sidecar-sidecar:latest
    container_name: user-sidecar
    restart: no
    environment:
      - GLOG_logtostderr=1
#      - GLOG_v=1
    volumes:
      - ./.configs/user.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4006:4006" # egress_listener_port
      - "3006:3006"   # ingress_listener_port
    privileged: true
    cpuset: "34,35"