services:

  ingress-plain:
    image: sidecar-sidecar:latest
    container_name: ingress-plain
    restart: no
    environment:
      - PROC_NAME=ingress-plain
      - GLOG_logtostderr=1
    volumes:
      - ./.configs/ingress-plain.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "3000:3000"   # hotels listen_port
    privileged: true
    cpuset: "22,23"

  ingress-sidecar:
    image: sidecar-sidecar:latest
    container_name: ingress-sidecar
    restart: no
    environment:
      - PROC_NAME=ingress-sidecar
      - GLOG_logtostderr=1
#      - GLOG_v=1
#      - GLOG_vmodule=stats=1
#      - GLOG_vmodule=ingress=2,state=2
    volumes:
      - ./.configs/ingress.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4000:4000" # egress_listener_port
      - "3000:3000"   # hotels listen_port
      - "3009:3009"   # reservation listen_port
    privileged: true
    cpuset: "22,23"

  frontend-sidecar:
    image: sidecar-sidecar:latest
    container_name: frontend-sidecar
    restart: no
    environment:
      - PROC_NAME=frontend-sidecar
      - GLOG_logtostderr=1
#      - GLOG_v=1
#      - GLOG_vmodule=stats=1
#      - GLOG_vmodule=ingress=2,state=2
    volumes:
      - ./.configs/frontend.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4007:4007" # egress_listener_port
      - "3007:3007"   # ingress_listener_port
    privileged: true
    cpuset: "20,21"
  
  profile-sidecar:
    image: sidecar-sidecar:latest
    container_name: profile-sidecar
    restart: no
    environment:
      - PROC_NAME=profile-sidecar
      - GLOG_logtostderr=1
#      - GLOG_v=1
#      - GLOG_vmodule=stats=1
#      - GLOG_vmodule=ingress=2,state=2
    volumes:
      - ./.configs/profile.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4001:4001" # egress_listener_port
      - "3001:3001"   # ingress_listener_port
    privileged: true
    cpuset: "18,19"
  
  reservation-sidecar:
    image: sidecar-sidecar:latest
    container_name: reservation-sidecar
    restart: no
    environment:
      - PROC_NAME=reservation-sidecar
      - GLOG_logtostderr=1
#      - GLOG_v=1
#      - GLOG_vmodule=stats=1
#      - GLOG_vmodule=ingress=2,state=2
    volumes:
      - ./.configs/reservation.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4002:4002" # egress_listener_port
      - "3002:3002"   # ingress_listener_port
    privileged: true
    cpuset: "16,17"
  
  search-sidecar:
    image: sidecar-sidecar:latest
    container_name: search-sidecar
    restart: no
    environment:
      - PROC_NAME=search-sidecar
      - GLOG_logtostderr=1
#      - GLOG_v=1
#      - GLOG_vmodule=state=1
#      - GLOG_vmodule=stats=1
#      - GLOG_vmodule=ingress=2,state=2
    volumes:
      - ./.configs/search.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4005:4005" # egress_listener_port
      - "3005:3005"   # ingress_listener_port
    privileged: true
    cpuset: "14,15"
  
  geo-sidecar:
    image: sidecar-sidecar:latest
    container_name: geo-sidecar
    restart: no
    environment:
      - PROC_NAME=geo-sidecar
      - GLOG_logtostderr=1
#      - GLOG_v=1
#      - GLOG_vmodule=stats=1
#      - GLOG_vmodule=ingress=2,state=2
    volumes:
      - ./.configs/geo.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4004:4004" # egress_listener_port
      - "3004:3004"   # ingress_listener_port
    privileged: true
    cpuset: "12,13"
  
  rate-sidecar:
    image: sidecar-sidecar:latest
    container_name: rate-sidecar
    restart: no
    environment:
      - PROC_NAME=rate-sidecar
      - GLOG_logtostderr=1
#      - GLOG_v=1
#      - GLOG_vmodule=stats=1
#      - GLOG_vmodule=ingress=2,state=2
    volumes:
      - ./.configs/rate.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4003:4003" # egress_listener_port
      - "3003:3003"   # ingress_listener_port
    privileged: true
    cpuset: "10,11"
  
#  user-sidecar:
#    image: sidecar-sidecar:latest
#    container_name: user-sidecar
#    restart: no
#    environment:
#      - PROC_NAME=user-sidecar
#      - GLOG_logtostderr=1
##      - GLOG_v=1
##      - GLOG_vmodule=stats=1
##      - GLOG_vmodule=ingress=2,state=2
#    volumes:
#      - ./.configs/user.yaml:/config.yaml
#      - /usr/local/lib:/usr/local/lib:ro
#      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
#    ports:
#      - "4006:4006" # egress_listener_port
#      - "3006:3006"   # ingress_listener_port
#    privileged: true
#    cpuset: "13,14"