syntax = "proto3";

package protobuf;

option go_package = "social/protobuf";

import "post.proto";

service HomeTimeline {
  rpc ReadHomeTimeline(ReadHomeTimelineRequest) returns (ReadHomeTimelineResponse);
  rpc WriteHomeTimeline(WriteHomeTimelineRequest) returns (WriteHomeTimelineResponse);
}

message ReadHomeTimelineRequest {
  string user_id = 1;
}

message ReadHomeTimelineResponse {
  repeated Post posts = 1;
}

message WriteHomeTimelineRequest {
  string user_id = 1;
  repeated string post_ids = 2;
}

message WriteHomeTimelineResponse {
  bool success = 1;
}