apiVersion: v1
data:
  ClientPort: "2007"
  FrontendGRPCAddr: frontend-grpc:2009
  FrontendGRPCPort: "2009"
  FrontendPort: "2007"
  GeoAddr: hotel-geo:2004
  GeoMongoAddress: mongodb-geo:27017
  GeoPort: "2004"
  ProfileAddr: hotel-profile:2001
  ProfileMemcAddress: memcached-profile:11211
  ProfileMongoAddress: mongodb-profile:27017
  ProfilePort: "2001"
  RateAddr: hotel-rate:2003
  RateMemcAddress: memcached-rate:11211
  RateMongoAddress: mongodb-rate:27017
  RatePort: "2003"
  ReservationAddr: hotel-reservation:2002
  ReservationPort: "2002"
  ReserveMemcAddress: memcached-reserve:11211
  ReserveMongoAddress: mongodb-reservation:27017
  SearchAddr: hotel-search:2005
  SearchPort: "2005"
  UserAddr: hotel-user:2006
  UserMongoAddress: mongodb-user:27017
  UserPort: "2006"
  consulAddr: consul:8500
  dagor: "true"
  deployment: hotel
  jaegerAddress: jaeger:14268
kind: ConfigMap
metadata:
  name: hotel-config
