networks:
  monitoring:
    name: monitoring

services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.108.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - 4317:4317
    networks:
      - monitoring
#    cpuset: "47"
  
#  influxdb3-core:
#    container_name: influxdb3-core
#    image: influxdb:3-core
#    ports:
#      - 8181:8181
#    command:
#      - influxdb3
#      - serve
#      - --node-id=node0
#      - --object-store=memory
#      - --without-auth
#      - --data-dir=/var/lib/influxdb3/data
#      - --plugin-dir=/var/lib/influxdb3/plugins
#    volumes:
#      - type: bind
#        source: ~/.influxdb3/core/data
#        target: /var/lib/influxdb3/data
#      - type: bind
#        source: ~/.influxdb3/core/plugins
#        target: /var/lib/influxdb3/plugins
#    cpuset: "46,47"
  
#  influxdb:
#    image: influxdb:2.0-alpine
#    container_name: influxdb
#    networks:
#      - monitoring
#    ports:
#      - "8086:8086"
#    environment:
#      - DOCKER_INFLUXDB_INIT_MODE=setup
#      - DOCKER_INFLUXDB_INIT_USERNAME=croco
#      - DOCKER_INFLUXDB_INIT_PASSWORD=password1
#      - DOCKER_INFLUXDB_INIT_ORG=k6io
#      - DOCKER_INFLUXDB_INIT_BUCKET=demo
#      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=EEKpryGZk8pVDXmIuy484BKUxM5jOEDv7YNoeNZUbsNbpbPbP6kK_qY9Zsyw7zNnlZ7pHG16FYzNaqwLMBUz8g==
#    cpuset: "46,47"

#  explorer:
#    image: influxdata/influxdb3-ui:1.2.0
#    networks:
#      - monitoring
#    container_name: influxdb3-explorer
#    ports:
#      - "8888:8888"
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.55.1
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9091:9090
    depends_on:
      - otel-collector
    networks:
      - monitoring
#    cpuset: "46"
  
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.60
    ports:
      - 16686:16686
      - 16685:16685     # For querying traces from jaeger
    depends_on:
      - otel-collector
    networks:
      - monitoring
    environment:
    - COLLECTOR_ZIPKIN_HOST_PORT=9411       # To collect envoy's traces
#    cpuset: "45"

  memcached-rate:
    image: memcached:latest
    hostname: user-memcached
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    ports:
      - "10003:11211"
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    cpuset: "44"
  
  memcached-profile:
    image: memcached:latest
    hostname: user-memcached
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    ports:
      - "10001:11211"
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    cpuset: "44"
    
  memcached-reserve:
    image: memcached:latest
    hostname: user-memcached
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    ports:
      - "10002:11211"
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    cpuset: "43"
  
  mongodb-geo:
    image: mongo:5.0
    hostname: geo-db
    volumes:
      - geo:/data/db
    restart: always
    ports:
      - "20004:27017"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    cpuset: "43"

  mongodb-profile:
    image: mongo:5.0
    hostname: profile-db
    volumes:
      - profile:/data/db
    restart: always
    ports:
      - "20001:27017"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    cpuset: "42"

  mongodb-rate:
    image: mongo:5.0
    hostname: rate-db
    volumes:
      - rate:/data/db
    restart: always
    ports:
      - "20003:27017"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    cpuset: "42"
  
  mongodb-reservation:
    image: mongo:5.0
    hostname: reservation-db
    volumes:
      - reservation:/data/db
    restart: always
    ports:
      - "20002:27017"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    cpuset: "41"
  
  mongodb-user:
    image: mongo:5.0
    hostname: user-db
    volumes:
      - user:/data/db
    ports:
      - "20006:27017"
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    cpuset: "41"

volumes:
  geo:
  profile:
  rate:
  recommendation:
  reservation:
  user:
  review:
  attractions: