services:

  ingress-sidecar:
    image: sidecar-sidecar:latest
    container_name: ingress-sidecar
    restart: no
    environment:
      - PROC_NAME=ingress-sidecar
      - GLOG_logtostderr=1
#      - GLOG_v=1
#      - GLOG_vmodule=ingress=1
    volumes:
      - ./.configs/ingress.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4000:4000" # egress_listener_port
      - "3000:3000"   # hotels listen_port
      - "3008:3008"   # home listen_port
      - "3009:3009"   # user listen_port
    privileged: true
    cpuset: "38,39,40"

  nginx-sidecar:
    image: sidecar-sidecar:latest
    container_name: nginx-sidecar
    restart: no
    environment:
      - PROC_NAME=nginx-sidecar
      - GLOG_logtostderr=1
#      - GLOG_v=1
#      - GLOG_vmodule=stats=2
    volumes:
      - ./.configs/nginx.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4007:4007" # egress_listener_port
      - "3007:3007"   # ingress_listener_port
    privileged: true
    cpuset: "36,37"
  
  compose-sidecar:
    image: sidecar-sidecar:latest
    container_name: compose-sidecar
    restart: no
    environment:
      - PROC_NAME=compose-sidecar
      - GLOG_logtostderr=1
#      - GLOG_v=1
    volumes:
      - ./.configs/compose.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4005:4005" # egress_listener_port
      - "3005:3005"   # ingress_listener_port
    privileged: true
    cpuset: "34,35"
  
  home-sidecar:
    image: sidecar-sidecar:latest
    container_name: home-sidecar
    restart: no
    environment:
      - PROC_NAME=home-sidecar
      - GLOG_logtostderr=1
#      - GLOG_v=1
    volumes:
      - ./.configs/home.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4002:4002" # egress_listener_port
      - "3002:3002"   # ingress_listener_port
    privileged: true
    cpuset: "32,33"
  
  user-sidecar:
    image: sidecar-sidecar:latest
    container_name: user-sidecar
    restart: no
    environment:
      - PROC_NAME=user-sidecar
      - GLOG_logtostderr=1
#      - GLOG_v=1
#      - GLOG_vmodule=state=1
    volumes:
      - ./.configs/user.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4001:4001" # egress_listener_port
      - "3001:3001"   # ingress_listener_port
    privileged: true
    cpuset: "30,31"
  
  posts-sidecar:
    image: sidecar-sidecar:latest
    container_name: posts-sidecar
    restart: no
    environment:
      - PROC_NAME=posts-sidecar
      - GLOG_logtostderr=1
#      - GLOG_v=1
    volumes:
      - ./.configs/posts.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4003:4003" # egress_listener_port
      - "3003:3003"   # ingress_listener_port
    privileged: true
    cpuset: "28,29"
  
  graph-sidecar:
    image: sidecar-sidecar:latest
    container_name: graph-sidecar
    restart: no
    environment:
      - PROC_NAME=graph-sidecar
      - GLOG_logtostderr=1
#      - GLOG_v=1
#      - GLOG_vmodule=stats=2
    volumes:
      - ./.configs/graph.yaml:/config.yaml
      - /usr/local/lib:/usr/local/lib:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
    ports:
      - "4004:4004" # egress_listener_port
      - "3004:3004"   # ingress_listener_port
    privileged: true
    cpuset: "26,27"